instrumentation:
  root: src
  extensions:
    - .es6
reporting:
    print: summary
    reports:
        - lcov
    dir: ./doc/coverage/
    watermarks:
        statements: [50, 80]
        lines: [50, 80]
        functions: [50, 80]
        branches: [50, 80]
